version: "3.8"

services:
  web:
    build: .
    container_name: employees
    restart: always
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input --clear && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
